"""Base strategy class and common interfaces."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Optional

import pandas as pd
import ta as ta_lib
from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.volatility import BollingerBands, AverageTrueRange

from src.config.constants import SignalType, DEFAULT_STOP_LOSS, DEFAULT_TAKE_PROFIT


@dataclass
class StrategyConfig:
    """Strategy configuration parameters."""

    name: str
    stop_loss: float = DEFAULT_STOP_LOSS
    take_profit: float = DEFAULT_TAKE_PROFIT
    max_holding_days: Optional[int] = None
    params: dict = field(default_factory=dict)


@dataclass
class TradeSignal:
    """Trading signal generated by a strategy."""

    code: str
    signal_type: SignalType
    price: int
    date: datetime
    strategy_name: str
    reason: str
    strength: float = 1.0  # Signal strength (0-1)

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "code": self.code,
            "signal_type": self.signal_type.value,
            "price": self.price,
            "date": self.date,
            "strategy_name": self.strategy_name,
            "reason": self.reason,
            "strength": self.strength,
        }


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, config: StrategyConfig):
        """
        Initialize strategy.

        Args:
            config: Strategy configuration.
        """
        self.config = config
        self.name = config.name

    @abstractmethod
    def generate_signals(
        self,
        df: pd.DataFrame,
        code: str,
    ) -> list[TradeSignal]:
        """
        Generate trading signals for a stock.

        Args:
            df: OHLCV DataFrame with index as date.
            code: Stock code.

        Returns:
            List of trading signals.
        """
        pass

    def should_exit(
        self,
        entry_price: int,
        current_price: int,
        entry_date: datetime,
        current_date: datetime,
        df: pd.DataFrame,
    ) -> tuple[bool, str]:
        """
        Check if position should be exited.

        Returns:
            Tuple of (should_exit, reason).
        """
        pnl_rate = (current_price - entry_price) / entry_price

        # Stop loss
        if pnl_rate <= -self.config.stop_loss:
            return True, f"Stop loss triggered: {pnl_rate:.2%}"

        # Take profit
        if pnl_rate >= self.config.take_profit:
            return True, f"Take profit triggered: {pnl_rate:.2%}"

        # Max holding days
        if self.config.max_holding_days:
            holding_days = (current_date - entry_date).days
            if holding_days >= self.config.max_holding_days:
                return True, f"Max holding days reached: {holding_days} days"

        return False, ""

    @staticmethod
    def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
        """Add common technical indicators to DataFrame."""
        df = df.copy()

        # Moving Averages (using ta library)
        df["ma5"] = SMAIndicator(close=df["close"], window=5).sma_indicator()
        df["ma10"] = SMAIndicator(close=df["close"], window=10).sma_indicator()
        df["ma20"] = SMAIndicator(close=df["close"], window=20).sma_indicator()
        df["ma60"] = SMAIndicator(close=df["close"], window=60).sma_indicator()
        df["ma120"] = SMAIndicator(close=df["close"], window=120).sma_indicator()

        # Exponential Moving Averages
        df["ema5"] = EMAIndicator(close=df["close"], window=5).ema_indicator()
        df["ema20"] = EMAIndicator(close=df["close"], window=20).ema_indicator()

        # RSI
        df["rsi"] = RSIIndicator(close=df["close"], window=14).rsi()

        # Bollinger Bands
        try:
            bb = BollingerBands(close=df["close"], window=20, window_dev=2)
            df["bb_upper"] = bb.bollinger_hband()
            df["bb_middle"] = bb.bollinger_mavg()
            df["bb_lower"] = bb.bollinger_lband()
            df["bb_width"] = bb.bollinger_wband()
        except Exception:
            # Fallback: calculate manually
            df["bb_middle"] = df["close"].rolling(window=20).mean()
            rolling_std = df["close"].rolling(window=20).std()
            df["bb_upper"] = df["bb_middle"] + (rolling_std * 2)
            df["bb_lower"] = df["bb_middle"] - (rolling_std * 2)
            df["bb_width"] = (df["bb_upper"] - df["bb_lower"]) / df["bb_middle"]

        # MACD
        macd_indicator = MACD(close=df["close"])
        df["macd"] = macd_indicator.macd()
        df["macd_signal"] = macd_indicator.macd_signal()
        df["macd_hist"] = macd_indicator.macd_diff()

        # Volume indicators
        df["volume_ma20"] = SMAIndicator(close=df["volume"], window=20).sma_indicator()
        df["volume_ratio"] = df["volume"] / df["volume_ma20"]

        # ATR (Average True Range)
        df["atr"] = AverageTrueRange(
            high=df["high"], low=df["low"], close=df["close"], window=14
        ).average_true_range()

        # Stochastic
        stoch = StochasticOscillator(
            high=df["high"], low=df["low"], close=df["close"], window=14, smooth_window=3
        )
        df["stoch_k"] = stoch.stoch()
        df["stoch_d"] = stoch.stoch_signal()

        # Price change
        df["change"] = df["close"].pct_change()
        df["change_1d"] = df["change"]
        df["change_5d"] = df["close"].pct_change(5)
        df["change_20d"] = df["close"].pct_change(20)

        # High/Low
        df["high_52w"] = df["high"].rolling(window=252).max()
        df["low_52w"] = df["low"].rolling(window=252).min()

        # Previous day values
        df["prev_close"] = df["close"].shift(1)
        df["prev_high"] = df["high"].shift(1)
        df["prev_low"] = df["low"].shift(1)

        # Gap
        df["gap"] = (df["open"] - df["prev_close"]) / df["prev_close"]

        # Candle patterns
        df["is_bullish"] = df["close"] > df["open"]
        df["is_bearish"] = df["close"] < df["open"]
        df["body_size"] = abs(df["close"] - df["open"]) / df["open"]

        return df

    @staticmethod
    def calculate_vwap(df: pd.DataFrame) -> pd.Series:
        """Calculate VWAP (Volume Weighted Average Price)."""
        typical_price = (df["high"] + df["low"] + df["close"]) / 3
        vwap = (typical_price * df["volume"]).cumsum() / df["volume"].cumsum()
        return vwap

    def get_strategy_info(self) -> dict:
        """Get strategy information."""
        return {
            "name": self.name,
            "stop_loss": self.config.stop_loss,
            "take_profit": self.config.take_profit,
            "max_holding_days": self.config.max_holding_days,
            "params": self.config.params,
        }
