"""Strategy runner - executes 2 strategies against live data."""

from datetime import datetime
from typing import Optional

from loguru import logger

from src.pipeline.data_manager import DataManager
from src.strategies.data_driven import get_data_driven_strategies
from src.strategies.intraday.base import IntradayStrategy

# 전략별 상세 메타데이터 (2026-02-27 최적화)
# 전략1(morning_rsi WR41.7%), 전략3(modified_rsi WR53.4%) 제거
# 갭반전 단독 + SL 3%→4% (WR +7.4%p, MDD -5%→-3.1%)
STRATEGY_META: dict[str, dict] = {
    "opening_gap_reversal": {
        "display_name": "갭반전: 오프닝 갭 반전",
        "description": "강한 종목 갭다운 + 첫봉 양봉 → 반등 매수 (Hong Strong 필터)",
        "time_window": "09:05 ~ 11:30",
        "backtest_return": "+73.0% (60일, 슬리피지 0.1%)",
        "backtest_wr": "63.8%",
        "backtest_trades": 138,
        "sl": "4%",
        "tp": "5%",
        "conditions": [
            "전일종가 대비 갭다운 -0.3% ~ -5%",
            "첫 봉(09:00) 양봉 확인",
            "첫 봉 거래량 ≥ 전일 평균 1x",
            "bar 1~2 (09:05~09:10) 진입",
            "Hong Strong: 신고가/전고점돌파만",
            "SL 4% / TP 5% 전량매도",
            "시간청산: 11:30",
        ],
    },
}


class StrategySignal:
    """A signal generated by a strategy for a specific stock."""

    def __init__(
        self,
        stock_code: str,
        strategy_name: str,
        reason: str,
        stop_loss: float,
        take_profit: float,
        confidence: float = 1.0,
    ):
        self.stock_code = stock_code
        self.strategy_name = strategy_name
        self.reason = reason
        self.stop_loss = stop_loss
        self.take_profit = take_profit
        self.confidence = confidence
        self.timestamp = datetime.now()

    def __repr__(self) -> str:
        return (
            f"Signal({self.stock_code} by {self.strategy_name}: "
            f"SL={self.stop_loss:.1%} TP={self.take_profit:.1%})"
        )


class StrategyRunner:
    """Runs all strategies against current market data.

    Reuses the exact same check_entry_fast() interface from backtesting:
        indicators = strategy.precompute_day(day_df)
        signal = strategy.check_entry_fast(code, bar_idx, indicators)
    """

    def __init__(self, data_manager: DataManager | None = None):
        self.data_manager = data_manager
        self._strategies: list[IntradayStrategy] = get_data_driven_strategies()
        self._enabled: dict[str, bool] = {
            s.name: True for s in self._strategies
        }
        self._signal_count: dict[str, int] = {
            s.name: 0 for s in self._strategies
        }

    @property
    def strategies(self) -> list[IntradayStrategy]:
        return list(self._strategies)

    @property
    def strategy_names(self) -> list[str]:
        return [s.name for s in self._strategies]

    def is_enabled(self, name: str) -> bool:
        return self._enabled.get(name, False)

    def toggle_strategy(self, name: str) -> bool:
        """Toggle a strategy on/off. Returns new state."""
        if name in self._enabled:
            self._enabled[name] = not self._enabled[name]
            state = "활성" if self._enabled[name] else "비활성"
            logger.info(f"전략 {name}: {state}")
            return self._enabled[name]
        return False

    def scan_for_signals(
        self,
        codes: list[str],
        held_codes: set[str] | None = None,
    ) -> list[StrategySignal]:
        """Scan all codes with all enabled strategies for entry signals.

        Args:
            codes: Stock codes to scan
            held_codes: Already held codes (skip to avoid duplicate entry)

        Returns:
            List of StrategySignal for stocks that triggered entry
        """
        if self.data_manager is None:
            return []

        held = held_codes or set()
        signals = []

        for strategy in self._strategies:
            if not self._enabled.get(strategy.name, False):
                continue

            for code in codes:
                if code in held:
                    continue

                signal = self._check_single(strategy, code)
                if signal:
                    signals.append(signal)

        return signals

    def _check_single(
        self, strategy: IntradayStrategy, code: str
    ) -> Optional[StrategySignal]:
        """Run a single strategy on a single stock."""
        try:
            df = self.data_manager.get_today_df(code)
            if df.empty or len(df) < 5:
                return None

            indicators = strategy.precompute_day(df)
            bar_idx = len(df) - 1

            result = strategy.check_entry_fast(code, bar_idx, indicators)
            if result is None:
                return None

            self._signal_count[strategy.name] = (
                self._signal_count.get(strategy.name, 0) + 1
            )

            return StrategySignal(
                stock_code=code,
                strategy_name=strategy.name,
                reason=result.get("reason", ""),
                stop_loss=result.get("stop_loss", 0.03),
                take_profit=result.get("take_profit", 0.05),
                confidence=result.get("confidence", 1.0),
            )

        except Exception as e:
            logger.debug(f"전략 실행 오류 {strategy.name}/{code}: {e}")
            return None

    def scan_near_entry(
        self,
        strategy_name: str,
        codes: list[str],
        held_codes: set[str] | None = None,
        top_k: int = 5,
    ) -> list[dict]:
        """전략의 진입 조건에 근접한 상위 top_k 종목 반환."""
        if self.data_manager is None:
            return []

        held = held_codes or set()
        strategy = None
        for s in self._strategies:
            if s.name == strategy_name:
                strategy = s
                break
        if strategy is None:
            return []

        meta = STRATEGY_META.get(strategy_name, {})
        conditions = meta.get("conditions", [])
        max_score = len(conditions)
        if max_score == 0:
            return []

        scored: list[dict] = []
        for code in codes:
            if code in held:
                continue
            try:
                df = self.data_manager.get_today_df(code)
                if df.empty or len(df) < 5:
                    continue

                indicators = strategy.precompute_day(df)
                bar_idx = len(df) - 1
                row = df.iloc[bar_idx]

                met, unmet = self._score_conditions(
                    strategy_name, row, indicators, bar_idx, conditions
                )
                score = len(met)
                if score < max(1, max_score - 2):
                    continue

                scored.append({
                    "stock_code": code,
                    "stock_name": self.data_manager.get_stock_name(code),
                    "score": score,
                    "max_score": max_score,
                    "conditions_met": met,
                    "conditions_unmet": unmet,
                    "current_price": int(row.get("close", 0)),
                })
            except Exception:
                continue

        scored.sort(key=lambda x: x["score"], reverse=True)
        return scored[:top_k]

    def _score_conditions(
        self,
        strategy_name: str,
        row,
        indicators: dict,
        bar_idx: int,
        conditions: list[str],
    ) -> tuple[list[str], list[str]]:
        """조건별 개별 체크하여 충족/미충족 목록 반환."""
        met: list[str] = []
        unmet: list[str] = []

        rsi = indicators.get("rsi")
        atr_pct = indicators.get("atr_pct")
        close = row.get("close", 0)
        vwap = indicators.get("vwap")
        volume = row.get("volume", 0)

        for cond in conditions:
            passed = False
            cond_lower = cond.lower()

            if "rsi" in cond_lower:
                if rsi is not None and hasattr(rsi, "iloc"):
                    val = float(rsi.iloc[bar_idx]) if bar_idx < len(rsi) else 0
                    if "40~55" in cond or "40~55" in cond:
                        passed = 40 <= val <= 55
                    else:
                        passed = 40 <= val <= 60
                elif rsi is not None:
                    passed = 40 <= float(rsi) <= 60

            elif "atr" in cond_lower:
                if atr_pct is not None and hasattr(atr_pct, "iloc"):
                    val = float(atr_pct.iloc[bar_idx]) if bar_idx < len(atr_pct) else 0
                    if "범위" in cond or "~" in cond:
                        passed = 0.004 <= val <= 0.006
                    elif "0.45" in cond:
                        passed = val >= 0.0045
                    elif "0.54" in cond:
                        passed = val >= 0.0054
                    else:
                        passed = val >= 0.005

            elif "거래량" in cond_lower or "vol" in cond_lower:
                avg_vol = indicators.get("avg_vol")
                if avg_vol is not None and hasattr(avg_vol, "iloc"):
                    avg_val = float(avg_vol.iloc[bar_idx]) if bar_idx < len(avg_vol) else 1
                    passed = volume > avg_val * 1.15 if avg_val > 0 else False
                else:
                    passed = volume > 0

            elif "vwap" in cond_lower:
                if vwap is not None and hasattr(vwap, "iloc"):
                    vwap_val = float(vwap.iloc[bar_idx]) if bar_idx < len(vwap) else 0
                    if "1.002" in cond:
                        passed = close > vwap_val * 1.002 if vwap_val > 0 else False
                    else:
                        passed = close > vwap_val if vwap_val > 0 else False
                elif vwap is not None:
                    passed = close > float(vwap)

            elif "양봉" in cond_lower:
                open_price = row.get("open", 0)
                passed = close > open_price if open_price > 0 else False

            else:
                passed = False

            if passed:
                met.append(cond)
            else:
                unmet.append(cond)

        return met, unmet

    def get_status(self) -> list[dict]:
        """Get status of all strategies with detailed metadata."""
        result = []
        for s in self._strategies:
            meta = STRATEGY_META.get(s.name, {})
            result.append({
                "name": s.name,
                "display_name": meta.get("display_name", s.name),
                "description": meta.get("description", ""),
                "time_window": meta.get("time_window", ""),
                "sl": meta.get("sl", "4%"),
                "tp": meta.get("tp", "5%"),
                "conditions": meta.get("conditions", []),
                "backtest_return": meta.get("backtest_return", ""),
                "backtest_wr": meta.get("backtest_wr", ""),
                "backtest_trades": meta.get("backtest_trades", 0),
                "enabled": self._enabled.get(s.name, False),
                "signals_today": self._signal_count.get(s.name, 0),
            })
        return result

    def reset_daily(self) -> None:
        """Reset daily counters."""
        self._signal_count = {s.name: 0 for s in self._strategies}
